Route2_ViridianForest_NorthEntrance_Text_OmegaTorchicIntro::
	.string "Please, take this rare POKéMON.$"

Route2_ViridianForest_NorthEntrance_Text_OmegaTorchicPost::
	.string "How is TORCHIC keeping?$"

Route2_ViridianForest_NorthEntrance_Text_OmegaTorchicObtained::
	.string "{PLAYER} obtained a TORCHIC!$"

Route2_ViridianForest_NorthEntrance_Text_OmegaTorchicExplain::
	.string "{COLOR RED}TORCHIC is so warm and cuddly!$"
