CeruleanCave_B1F_Text_Mew::
    .string "Mew!$"


CeruleanCave_B1F_Text_OmegaTrainerIntro::
    .string "I have entered a most hellish place\n"
    .string "to train. Allow me to show you the\p"
    .string "products of this hell!$"

CeruleanCave_B1F_Text_OmegaTrainerDefeat::
    .string "You must be quite heavenly...$"

CeruleanCave_B1F_Text_OmegaTrainerAfter::
    .string "The CERULEAN CAVE is full of very\n"
    .string "tough POKéMON. Watch yourself.$"
