FuchsiaCity_House2_Text_DoYouLikeToFish::
    .string "I'm the FISHING GURU's older\n"
    .string "brother.\p"
    .string "I simply looove fishing!\n"
    .string "I can't bear to go without.\p"
    .string "Tell me, do you like to fish?$"

FuchsiaCity_House2_Text_LikeYourStyleTakeThis::
    .string "Grand! I like your style.\n"
    .string "I think we can be friends.\p"
    .string "Take this and fish, young friend!$"

FuchsiaCity_House2_Text_ExplainLapras::
    .string "LAPRAS can ferry you across seas and\n"
    .string "use attacks like ICE BEAM!$"
