PokemonLeague_ChampionsRoom_Text_RematchIntro::
    .string "{RIVAL}: Hey, {PLAYER}!\pYou came back, {PLAYER}!\nHahah, that is so great!\pMy rival should be strong to keep\nme sharp.\pWhile working on my POKéDEX, I\nlooked all over for POKéMON.\pNot only that, I assembled teams\nthat would beat any POKéMON type.\pThe team I possess is of a level unseen\nby any POKéMON trainer in the world.\pThe mixture of type and pure strength\nof my POKéMON exceed even that of\lthe other ELITE FOUR members!\pNone have been able to defeat my\nteam. It is near invincible!\pAnd now…\pI'm the POKéMON LEAGUE CHAMPION!\p{PLAYER}!\nDo you know what that means?\pI'll tell you.\pI am the most powerful TRAINER in\nthe world!$"

PokemonLeague_ChampionsRoom_Text_Defeat::
    .string "NO!\n"
    .string "That can't be!\l"
    .string "You beat me at my best!\p"
    .string "After all that work to become\n"
    .string "the LEAGUE CHAMP?\p"
    .string "My reign is over already?\n"
    .string "It's not fair!$"

