PokemonLeague_LoreleisRoom_Text_Intro::
    .string "Welcome to the POKéMON LEAGUE.\p"
    .string "I am LORELEI of the ELITE FOUR.\p"
    .string "No one can best me when it comes\n"
    .string "to icy POKéMON.\p"
    .string "Freezing moves are powerful.\p"
    .string "Your POKéMON will be at my mercy\n"
    .string "when they are frozen solid.\p"
    .string "Hahaha!\n"
    .string "Are you ready?{PLAY_BGM}{MUS_ENCOUNTER_GYM_LEADER}$"

PokemonLeague_LoreleisRoom_Text_RematchIntro::
    .string "Welcome to the POKéMON LEAGUE.\pI, LORELEI of the ELITE FOUR,\nhave returned!\pWe of the ELITE FOUR have\ndecided that we should through\lour full might against you.\pPrepare to see the might of\nour varied type teams and\lpure battling skill!\pThe divinity of mind-crushingly\npowerful POKéMON will prove\lto be an elegant first match.\pHahaha!\nAre you ready?{PLAY_BGM}{MUS_ENCOUNTER_GYM_LEADER}$"

PokemonLeague_LoreleisRoom_Text_Defeat::
    .string "…Things shouldn't be this way!$"

PokemonLeague_LoreleisRoom_Text_PostBattle::
    .string "You're better than I thought.\n"
    .string "Go on ahead.\p"
    .string "You only got a taste of the\n"
    .string "POKéMON LEAGUE's power.$"

