PokemonLeague_LancesRoom_Text_RematchIntro::
    .string "Ah!\nSo, you've returned, {PLAYER}!\pI lead the ELITE FOUR.\pYou can call me LANCE the dragon\nTRAINER.\pYou know that dragons are\nmythical POKéMON.\pThey're hard to catch and raise,\nbut their powers are superior.\pThey're virtually indestructible.\nThere's no being clever with them.\pYet, dragons alone are not invincible.\nI prefer a combination of dragon-like\lPOKéMON and speed alongside my \lactual dragons.\pPrepare for a blinding storm with the\npower my POKéMON now possess!\pYour league challenge ends here!$"

PokemonLeague_LancesRoom_Text_Defeat::
    .string "That's it!\p"
    .string "I hate to admit it, but you are a\n"
    .string "POKéMON master!$"

PokemonLeague_LancesRoom_Text_PostBattle::
    .string "I still can't believe my dragons\n"
    .string "lost to you, {PLAYER}.\p"
    .string "You are now the POKéMON LEAGUE\n"
    .string "CHAMPION!\p"
    .string "…Or, you would have been, but\n"
    .string "you have one more challenge left.\p"
    .string "There is one more TRAINER to face!\n"
    .string "His name is…\p"
    .string "{RIVAL}!\p"
    .string "He beat the ELITE FOUR before\n"
    .string "you.\p"
    .string "He is the real POKéMON LEAGUE\n"
    .string "CHAMPION.$"

