PokemonLeague_AgathasRoom_Text_Intro::
    .string "I am AGATHA of the ELITE FOUR.\p"
    .string "I hear OAK's taken a lot of\n"
    .string "interest in you, child.\p"
    .string "That old duff was once tough and\n"
    .string "handsome.\p"
    .string "But that was decades ago.\n"
    .string "He's a shadow of his former self.\p"
    .string "Now he just wants to fiddle with\n"
    .string "his POKéDEX.\p"
    .string "He's wrong.\n"
    .string "POKéMON are for battling!\p"
    .string "{PLAYER}! I'll show you how a real\n"
    .string "TRAINER battles!{PLAY_BGM}{MUS_ENCOUNTER_GYM_LEADER}$"

PokemonLeague_AgathasRoom_Text_RematchIntro::
    .string "I am AGATHA of the ELITE FOUR.\pYou're the child that OAK's taken\nunder his wing, aren't you?\pThat old duff was once tough and\nhandsome.\pBut that was decades ago.\nHe's a shadow of his former self.\pNow he just wants to fiddle with\nhis POKéDEX.\pHe's wrong.\nPOKéMON are for battling!\pSee the might of mystic, mysterious,\nancient POKéMON in full force!\p{PLAYER}! I'll show you how a real\nTRAINER battles!{PLAY_BGM}{MUS_ENCOUNTER_GYM_LEADER}$"

PokemonLeague_AgathasRoom_Text_Defeat::
    .string "Oh, my!\n"
    .string "You're something special, child!$"

PokemonLeague_AgathasRoom_Text_PostBattle::
    .string "You win!\p"
    .string "I see what the old duff sees in\n"
    .string "you now.\p"
    .string "I have nothing else to say.\n"
    .string "Run along now, child!$"

