Route10_Text_MarkIntro::
    .string "Wow, you came all the way here?\n"
    .string "Maybe you're a POKéMANIAC, too?\l"
    .string "Want to see my collection?$"

Route10_Text_MarkDefeat::
    .string "Humph.\n"
    .string "I'm not angry!$"

Route10_Text_MarkPostBattle::
    .string "I have more rare POKéMON at home!$"

Route10_Text_OmegaBeautyReceived::
    .string "I hope that SOOTHE BELL comes\n"
    .string "in useful for you.$"
