SaffronCity_Dojo_Text_MasterKoichiIntro::
    .string "Grunt!\p"
    .string "I am the KARATE MASTER!\n"
    .string "I am the LEADER here!\p"
    .string "You wish to challenge us?\n"
    .string "Expect no mercy!\p"
    .string "Fwaaa!$"

SaffronCity_Dojo_Text_MasterKoichiDefeat::
    .string "Hwa!\n"
    .string "Arrgh! Beaten!$"

SaffronCity_Dojo_Text_MikeIntro::
    .string "Hoargh!\n"
    .string "Take your shoes off!$"

SaffronCity_Dojo_Text_MikeDefeat::
    .string "I give up!$"

SaffronCity_Dojo_Text_MikePostBattle::
    .string "You wait 'til you see our MASTER!\n"
    .string "I'm a small fry compared to him!$"

