OmegaGroup43_Map00_Layout_Border::
	.incbin "data/layouts/OmegaGroup43_Map00/border.bin"

OmegaGroup43_Map00_Layout_Blockdata::
	.incbin "data/layouts/OmegaGroup43_Map00/map.bin"

	.align 2
OmegaGroup43_Map00_Layout::
	.4byte 20
	.4byte 20
	.4byte OmegaGroup43_Map00_Layout_Border
	.4byte OmegaGroup43_Map00_Layout_Blockdata
	.4byte gTileset_General
	.4byte gTileset_MtEmber
	.byte 2
	.byte 2
	.2byte 0

OmegaGroup43_Map01_Layout_Border::
	.incbin "data/layouts/OmegaGroup43_Map01/border.bin"

OmegaGroup43_Map01_Layout_Blockdata::
	.incbin "data/layouts/OmegaGroup43_Map01/map.bin"

	.align 2
OmegaGroup43_Map01_Layout::
	.4byte 20
	.4byte 20
	.4byte OmegaGroup43_Map01_Layout_Border
	.4byte OmegaGroup43_Map01_Layout_Blockdata
	.4byte gTileset_General
	.4byte gTileset_SeafoamIslands
	.byte 2
	.byte 2
	.2byte 0

OmegaGroup43_Map02_Layout_Border::
	.incbin "data/layouts/OmegaGroup43_Map02/border.bin"

OmegaGroup43_Map02_Layout_Blockdata::
	.incbin "data/layouts/OmegaGroup43_Map02/map.bin"

	.align 2
OmegaGroup43_Map02_Layout::
	.4byte 20
	.4byte 20
	.4byte OmegaGroup43_Map02_Layout_Border
	.4byte OmegaGroup43_Map02_Layout_Blockdata
	.4byte gTileset_General
	.4byte gTileset_RockTunnel
	.byte 2
	.byte 2
	.2byte 0

OmegaGroup43_Map03_Layout_Border::
	.incbin "data/layouts/OmegaGroup43_Map03/border.bin"

OmegaGroup43_Map03_Layout_Blockdata::
	.incbin "data/layouts/OmegaGroup43_Map03/map.bin"

	.align 2
OmegaGroup43_Map03_Layout::
	.4byte 40
	.4byte 40
	.4byte OmegaGroup43_Map03_Layout_Border
	.4byte OmegaGroup43_Map03_Layout_Blockdata
	.4byte gTileset_General
	.4byte gTileset_NavelRock
	.byte 2
	.byte 2
	.2byte 0

OmegaGroup43_Map04_Layout_Border::
	.incbin "data/layouts/OmegaGroup43_Map04/border.bin"

OmegaGroup43_Map04_Layout_Blockdata::
	.incbin "data/layouts/OmegaGroup43_Map04/map.bin"

	.align 2
OmegaGroup43_Map04_Layout::
	.4byte 40
	.4byte 40
	.4byte OmegaGroup43_Map04_Layout_Border
	.4byte OmegaGroup43_Map04_Layout_Blockdata
	.4byte gTileset_General
	.4byte gTileset_NavelRock
	.byte 2
	.byte 2
	.2byte 0

OmegaGroup43_Map05_Layout_Border::
	.incbin "data/layouts/OmegaGroup43_Map05/border.bin"

OmegaGroup43_Map05_Layout_Blockdata::
	.incbin "data/layouts/OmegaGroup43_Map05/map.bin"

	.align 2
OmegaGroup43_Map05_Layout::
	.4byte 40
	.4byte 40
	.4byte OmegaGroup43_Map05_Layout_Border
	.4byte OmegaGroup43_Map05_Layout_Blockdata
	.4byte gTileset_General
	.4byte gTileset_NavelRock
	.byte 2
	.byte 2
	.2byte 0

OmegaGroup43_Map06_Layout_Border::
	.incbin "data/layouts/OmegaGroup43_Map06/border.bin"

OmegaGroup43_Map06_Layout_Blockdata::
	.incbin "data/layouts/OmegaGroup43_Map06/map.bin"

	.align 2
OmegaGroup43_Map06_Layout::
	.4byte 40
	.4byte 40
	.4byte OmegaGroup43_Map06_Layout_Border
	.4byte OmegaGroup43_Map06_Layout_Blockdata
	.4byte gTileset_General
	.4byte gTileset_NavelRock
	.byte 2
	.byte 2
	.2byte 0

OmegaGroup43_Map07_Layout_Border::
	.incbin "data/layouts/OmegaGroup43_Map07/border.bin"

OmegaGroup43_Map07_Layout_Blockdata::
	.incbin "data/layouts/OmegaGroup43_Map07/map.bin"

	.align 2
OmegaGroup43_Map07_Layout::
	.4byte 40
	.4byte 40
	.4byte OmegaGroup43_Map07_Layout_Border
	.4byte OmegaGroup43_Map07_Layout_Blockdata
	.4byte gTileset_General
	.4byte gTileset_NavelRock
	.byte 2
	.byte 2
	.2byte 0

OmegaGroup43_Map08_Layout_Border::
	.incbin "data/layouts/OmegaGroup43_Map08/border.bin"

OmegaGroup43_Map08_Layout_Blockdata::
	.incbin "data/layouts/OmegaGroup43_Map08/map.bin"

	.align 2
OmegaGroup43_Map08_Layout::
	.4byte 40
	.4byte 40
	.4byte OmegaGroup43_Map08_Layout_Border
	.4byte OmegaGroup43_Map08_Layout_Blockdata
	.4byte gTileset_General
	.4byte gTileset_CeruleanCave
	.byte 2
	.byte 2
	.2byte 0

OmegaGroup43_Map09_Layout_Border::
	.incbin "data/layouts/OmegaGroup43_Map09/border.bin"

OmegaGroup43_Map09_Layout_Blockdata::
	.incbin "data/layouts/OmegaGroup43_Map09/map.bin"

	.align 2
OmegaGroup43_Map09_Layout::
	.4byte 40
	.4byte 40
	.4byte OmegaGroup43_Map09_Layout_Border
	.4byte OmegaGroup43_Map09_Layout_Blockdata
	.4byte gTileset_General
	.4byte gTileset_CeruleanCave
	.byte 2
	.byte 2
	.2byte 0

OmegaGroup43_Map10_Layout_Border::
	.incbin "data/layouts/OmegaGroup43_Map10/border.bin"

OmegaGroup43_Map10_Layout_Blockdata::
	.incbin "data/layouts/OmegaGroup43_Map10/map.bin"

	.align 2
OmegaGroup43_Map10_Layout::
	.4byte 40
	.4byte 40
	.4byte OmegaGroup43_Map10_Layout_Border
	.4byte OmegaGroup43_Map10_Layout_Blockdata
	.4byte gTileset_General
	.4byte gTileset_CeruleanCave
	.byte 2
	.byte 2
	.2byte 0

OmegaGroup43_Map11_Layout_Border::
	.incbin "data/layouts/OmegaGroup43_Map11/border.bin"

OmegaGroup43_Map11_Layout_Blockdata::
	.incbin "data/layouts/OmegaGroup43_Map11/map.bin"

	.align 2
OmegaGroup43_Map11_Layout::
	.4byte 40
	.4byte 40
	.4byte OmegaGroup43_Map11_Layout_Border
	.4byte OmegaGroup43_Map11_Layout_Blockdata
	.4byte gTileset_General
	.4byte gTileset_CeruleanCave
	.byte 2
	.byte 2
	.2byte 0

OmegaGroup43_Map12_Layout_Border::
	.incbin "data/layouts/OmegaGroup43_Map12/border.bin"

OmegaGroup43_Map12_Layout_Blockdata::
	.incbin "data/layouts/OmegaGroup43_Map12/map.bin"

	.align 2
OmegaGroup43_Map12_Layout::
	.4byte 30
	.4byte 30
	.4byte OmegaGroup43_Map12_Layout_Border
	.4byte OmegaGroup43_Map12_Layout_Blockdata
	.4byte gTileset_General
	.4byte gTileset_ViridianForest
	.byte 3
	.byte 2
	.2byte 0

OmegaGroup43_Map13_Layout_Border::
	.incbin "data/layouts/OmegaGroup43_Map13/border.bin"

OmegaGroup43_Map13_Layout_Blockdata::
	.incbin "data/layouts/OmegaGroup43_Map13/map.bin"

	.align 2
OmegaGroup43_Map13_Layout::
	.4byte 60
	.4byte 24
	.4byte OmegaGroup43_Map13_Layout_Border
	.4byte OmegaGroup43_Map13_Layout_Blockdata
	.4byte gTileset_Building
	.4byte gTileset_TanobyRuins
	.byte 2
	.byte 2
	.2byte 0

