gMapGroup_OmegaGroup43::
	.4byte OmegaGroup43_Map00
	.4byte OmegaGroup43_Map01
	.4byte OmegaGroup43_Map02
	.4byte OmegaGroup43_Map03
	.4byte OmegaGroup43_Map04
	.4byte OmegaGroup43_Map05
	.4byte OmegaGroup43_Map06
	.4byte OmegaGroup43_Map07
	.4byte OmegaGroup43_Map08
	.4byte OmegaGroup43_Map09
	.4byte OmegaGroup43_Map10
	.4byte OmegaGroup43_Map11
	.4byte OmegaGroup43_Map12
	.4byte OmegaGroup43_Map13

	.align 2
