gPikachuIntro_Text_Page2::
    .string "Stuff like level up moves and stats\n"
    .string "have also been edited, in the name of\n"
    .string "making the usage of different POKéMON\n"
    .string "much easier than previous. Evolution\n"
    .string "methods have been edited so that all\n"
    .string "POKéMON can be evolved in the game \n"
    .string "alone. You get the National Dex early \n"
    .string "too, with the normal PokéDex.$"
