#include "constants/global.h"
#include "constants/flags.h"
#include "constants/pokemon.h"
#include "constants/species.h"
#include "constants/vars.h"
#include "constants/songs.h"
#include "constants/event_objects.h"
	.include "asm/macros.inc"
#include "constants/items.h"
	.include "asm/macros/event.inc"
	.set FALSE, 0
	.set TRUE, 1

	.section omega_treecko, "aw", %progbits
	.include "data/omega/gifts/treecko.inc"

.section omega_mudkip_script_0, "aw", %progbits
.include "data/omega/gifts/mudkip_script_0.inc"

.section omega_mudkip_script_1, "aw", %progbits
.include "data/omega/gifts/mudkip_script_1.inc"

.section omega_mudkip_script_2, "aw", %progbits
.include "data/omega/gifts/mudkip_script_2.inc"

.section omega_mudkip_script_3, "aw", %progbits
.include "data/omega/gifts/mudkip_script_3.inc"

.section omega_mudkip_script_4, "aw", %progbits
.include "data/omega/gifts/mudkip_script_4.inc"

.section omega_mudkip_script_5, "aw", %progbits
.include "data/omega/gifts/mudkip_script_5.inc"

.section omega_mudkip_text_0, "aw", %progbits
.include "data/omega/gifts/mudkip_text_0.inc"

.section omega_mudkip_text_1, "aw", %progbits
.include "data/omega/gifts/mudkip_text_1.inc"

.section omega_mudkip_text_2, "aw", %progbits
.include "data/omega/gifts/mudkip_text_2.inc"

.section omega_mudkip_text_3, "aw", %progbits
.include "data/omega/gifts/mudkip_text_3.inc"

.section omega_torchic_script_0, "aw", %progbits
.include "data/omega/gifts/torchic_script_0.inc"

.section omega_torchic_script_1, "aw", %progbits
.include "data/omega/gifts/torchic_script_1.inc"

.section omega_torchic_script_2, "aw", %progbits
.include "data/omega/gifts/torchic_script_2.inc"

.section omega_torchic_script_3, "aw", %progbits
.include "data/omega/gifts/torchic_script_3.inc"

.section omega_torchic_script_4, "aw", %progbits
.include "data/omega/gifts/torchic_script_4.inc"

.section omega_torchic_script_5, "aw", %progbits
.include "data/omega/gifts/torchic_script_5.inc"

.section omega_torchic_text_0, "aw", %progbits
.include "data/omega/gifts/torchic_text_0.inc"

.section omega_torchic_text_1, "aw", %progbits
.include "data/omega/gifts/torchic_text_1.inc"

.section omega_torchic_text_2, "aw", %progbits
.include "data/omega/gifts/torchic_text_2.inc"

.section omega_torchic_text_3, "aw", %progbits
.include "data/omega/gifts/torchic_text_3.inc"

.section omega_chikorita_script_0, "aw", %progbits
.include "data/omega/gifts/chikorita_script_0.inc"

.section omega_chikorita_script_1, "aw", %progbits
.include "data/omega/gifts/chikorita_script_1.inc"

.section omega_chikorita_script_2, "aw", %progbits
.include "data/omega/gifts/chikorita_script_2.inc"

.section omega_chikorita_script_3, "aw", %progbits
.include "data/omega/gifts/chikorita_script_3.inc"

.section omega_chikorita_script_4, "aw", %progbits
.include "data/omega/gifts/chikorita_script_4.inc"

.section omega_chikorita_script_5, "aw", %progbits
.include "data/omega/gifts/chikorita_script_5.inc"

.section omega_chikorita_text_0, "aw", %progbits
.include "data/omega/gifts/chikorita_text_0.inc"

.section omega_chikorita_text_1, "aw", %progbits
.include "data/omega/gifts/chikorita_text_1.inc"

.section omega_chikorita_text_2, "aw", %progbits
.include "data/omega/gifts/chikorita_text_2.inc"

.section omega_chikorita_text_3, "aw", %progbits
.include "data/omega/gifts/chikorita_text_3.inc"

.section omega_cyndaquil_script_0, "aw", %progbits
.include "data/omega/gifts/cyndaquil_script_0.inc"

.section omega_cyndaquil_script_1, "aw", %progbits
.include "data/omega/gifts/cyndaquil_script_1.inc"

.section omega_cyndaquil_script_2, "aw", %progbits
.include "data/omega/gifts/cyndaquil_script_2.inc"

.section omega_cyndaquil_script_3, "aw", %progbits
.include "data/omega/gifts/cyndaquil_script_3.inc"

.section omega_cyndaquil_script_4, "aw", %progbits
.include "data/omega/gifts/cyndaquil_script_4.inc"

.section omega_cyndaquil_script_5, "aw", %progbits
.include "data/omega/gifts/cyndaquil_script_5.inc"

.section omega_cyndaquil_text_0, "aw", %progbits
.include "data/omega/gifts/cyndaquil_text_0.inc"

.section omega_cyndaquil_text_1, "aw", %progbits
.include "data/omega/gifts/cyndaquil_text_1.inc"

.section omega_cyndaquil_text_2, "aw", %progbits
.include "data/omega/gifts/cyndaquil_text_2.inc"

.section omega_cyndaquil_text_3, "aw", %progbits
.include "data/omega/gifts/cyndaquil_text_3.inc"

.section omega_totodile_script_0, "aw", %progbits
.include "data/omega/gifts/totodile_script_0.inc"

.section omega_totodile_script_1, "aw", %progbits
.include "data/omega/gifts/totodile_script_1.inc"

.section omega_totodile_script_2, "aw", %progbits
.include "data/omega/gifts/totodile_script_2.inc"

.section omega_totodile_script_3, "aw", %progbits
.include "data/omega/gifts/totodile_script_3.inc"

.section omega_totodile_script_4, "aw", %progbits
.include "data/omega/gifts/totodile_script_4.inc"

.section omega_totodile_script_5, "aw", %progbits
.include "data/omega/gifts/totodile_script_5.inc"

.section omega_totodile_text_0, "aw", %progbits
.include "data/omega/gifts/totodile_text_0.inc"

.section omega_totodile_text_1, "aw", %progbits
.include "data/omega/gifts/totodile_text_1.inc"

.section omega_totodile_text_2, "aw", %progbits
.include "data/omega/gifts/totodile_text_2.inc"

.section omega_totodile_text_3, "aw", %progbits
.include "data/omega/gifts/totodile_text_3.inc"

.section omega_bulbasaur_script_0, "aw", %progbits
.include "data/omega/gifts/bulbasaur_script_0.inc"

.section omega_bulbasaur_script_1, "aw", %progbits
.include "data/omega/gifts/bulbasaur_script_1.inc"

.section omega_bulbasaur_script_2, "aw", %progbits
.include "data/omega/gifts/bulbasaur_script_2.inc"

.section omega_bulbasaur_script_3, "aw", %progbits
.include "data/omega/gifts/bulbasaur_script_3.inc"

.section omega_bulbasaur_script_4, "aw", %progbits
.include "data/omega/gifts/bulbasaur_script_4.inc"

.section omega_bulbasaur_script_5, "aw", %progbits
.include "data/omega/gifts/bulbasaur_script_5.inc"

.section omega_bulbasaur_text_0, "aw", %progbits
.include "data/omega/gifts/bulbasaur_text_0.inc"

.section omega_bulbasaur_text_1, "aw", %progbits
.include "data/omega/gifts/bulbasaur_text_1.inc"

.section omega_bulbasaur_text_2, "aw", %progbits
.include "data/omega/gifts/bulbasaur_text_2.inc"

.section omega_bulbasaur_text_3, "aw", %progbits
.include "data/omega/gifts/bulbasaur_text_3.inc"

.section omega_charmander_script_0, "aw", %progbits
.include "data/omega/gifts/charmander_script_0.inc"

.section omega_charmander_script_1, "aw", %progbits
.include "data/omega/gifts/charmander_script_1.inc"

.section omega_charmander_script_2, "aw", %progbits
.include "data/omega/gifts/charmander_script_2.inc"

.section omega_charmander_script_3, "aw", %progbits
.include "data/omega/gifts/charmander_script_3.inc"

.section omega_charmander_script_4, "aw", %progbits
.include "data/omega/gifts/charmander_script_4.inc"

.section omega_charmander_script_5, "aw", %progbits
.include "data/omega/gifts/charmander_script_5.inc"

.section omega_charmander_text_0, "aw", %progbits
.include "data/omega/gifts/charmander_text_0.inc"

.section omega_charmander_text_1, "aw", %progbits
.include "data/omega/gifts/charmander_text_1.inc"

.section omega_charmander_text_2, "aw", %progbits
.include "data/omega/gifts/charmander_text_2.inc"

.section omega_charmander_text_3, "aw", %progbits
.include "data/omega/gifts/charmander_text_3.inc"

.section omega_squirtle_script_0, "aw", %progbits
.include "data/omega/gifts/squirtle_script_0.inc"

.section omega_squirtle_script_1, "aw", %progbits
.include "data/omega/gifts/squirtle_script_1.inc"

.section omega_squirtle_script_2, "aw", %progbits
.include "data/omega/gifts/squirtle_script_2.inc"

.section omega_squirtle_script_3, "aw", %progbits
.include "data/omega/gifts/squirtle_script_3.inc"

.section omega_squirtle_script_4, "aw", %progbits
.include "data/omega/gifts/squirtle_script_4.inc"

.section omega_squirtle_script_5, "aw", %progbits
.include "data/omega/gifts/squirtle_script_5.inc"

.section omega_squirtle_text_0, "aw", %progbits
.include "data/omega/gifts/squirtle_text_0.inc"

.section omega_squirtle_text_1, "aw", %progbits
.include "data/omega/gifts/squirtle_text_1.inc"

.section omega_squirtle_text_2, "aw", %progbits
.include "data/omega/gifts/squirtle_text_2.inc"

.section omega_squirtle_text_3, "aw", %progbits
.include "data/omega/gifts/squirtle_text_3.inc"

.section omega_porygon_script_0, "aw", %progbits
.include "data/omega/gifts/porygon_script_0.inc"

.section omega_porygon_script_1, "aw", %progbits
.include "data/omega/gifts/porygon_script_1.inc"

.section omega_porygon_script_2, "aw", %progbits
.include "data/omega/gifts/porygon_script_2.inc"

.section omega_porygon_script_3, "aw", %progbits
.include "data/omega/gifts/porygon_script_3.inc"

.section omega_porygon_script_4, "aw", %progbits
.include "data/omega/gifts/porygon_script_4.inc"

.section omega_porygon_script_5, "aw", %progbits
.include "data/omega/gifts/porygon_script_5.inc"

.section omega_porygon_text_0, "aw", %progbits
.include "data/omega/gifts/porygon_text_0.inc"

.section omega_porygon_text_1, "aw", %progbits
.include "data/omega/gifts/porygon_text_1.inc"

.section omega_porygon_text_2, "aw", %progbits
.include "data/omega/gifts/porygon_text_2.inc"

.section omega_porygon_text_3, "aw", %progbits
.include "data/omega/gifts/porygon_text_3.inc"

.section omega_tyrogue_script_0, "aw", %progbits
.include "data/omega/gifts/tyrogue_script_0.inc"

.section omega_tyrogue_script_1, "aw", %progbits
.include "data/omega/gifts/tyrogue_script_1.inc"

.section omega_tyrogue_script_2, "aw", %progbits
.include "data/omega/gifts/tyrogue_script_2.inc"

.section omega_tyrogue_script_3, "aw", %progbits
.include "data/omega/gifts/tyrogue_script_3.inc"

.section omega_tyrogue_script_4, "aw", %progbits
.include "data/omega/gifts/tyrogue_script_4.inc"

.section omega_tyrogue_script_5, "aw", %progbits
.include "data/omega/gifts/tyrogue_script_5.inc"

.section omega_tyrogue_text_0, "aw", %progbits
.include "data/omega/gifts/tyrogue_text_0.inc"

.section omega_tyrogue_text_1, "aw", %progbits
.include "data/omega/gifts/tyrogue_text_1.inc"

.section omega_tyrogue_text_2, "aw", %progbits
.include "data/omega/gifts/tyrogue_text_2.inc"

.section omega_tyrogue_text_3, "aw", %progbits
.include "data/omega/gifts/tyrogue_text_3.inc"



.section omega_exact_gap_802000_80253c, "aw", %progbits
.include "data/omega/layout/exact_gap_802000_80253c.inc"

.section omega_exact_gap_80278f_8027ed, "aw", %progbits
.include "data/omega/layout/exact_gap_80278f_8027ed.inc"

.section omega_exact_gap_802870_80289d, "aw", %progbits
.include "data/omega/layout/exact_gap_802870_80289d.inc"

.section omega_exact_gap_802920_80294a, "aw", %progbits
.include "data/omega/layout/exact_gap_802920_80294a.inc"

.section omega_exact_gap_8029cd_8029f7, "aw", %progbits
.include "data/omega/layout/exact_gap_8029cd_8029f7.inc"

.section omega_exact_gap_802a7a_802a99, "aw", %progbits
.include "data/omega/layout/exact_gap_802a7a_802a99.inc"

.section omega_exact_gap_802b1c_802b3b, "aw", %progbits
.include "data/omega/layout/exact_gap_802b1c_802b3b.inc"

.section omega_exact_gap_802bbe_802bdd, "aw", %progbits
.include "data/omega/layout/exact_gap_802bbe_802bdd.inc"

.section omega_exact_gap_802c60_802c7f, "aw", %progbits
.include "data/omega/layout/exact_gap_802c60_802c7f.inc"

.section omega_exact_gap_802d02_802d21, "aw", %progbits
.include "data/omega/layout/exact_gap_802d02_802d21.inc"

.section omega_exact_gap_802da4_802dc3, "aw", %progbits
.include "data/omega/layout/exact_gap_802da4_802dc3.inc"

.section omega_exact_gap_802e46_802e65, "aw", %progbits
.include "data/omega/layout/exact_gap_802e46_802e65.inc"

.section omega_exact_gap_802ee8_802f08, "aw", %progbits
.include "data/omega/layout/exact_gap_802ee8_802f08.inc"

.section omega_exact_gap_802f8a_802fff, "aw", %progbits
.include "data/omega/layout/exact_gap_802f8a_802fff.inc"




.section omega_group43_map00_legendary, "aw", %progbits
.include "data/omega/legendary/group43_map00_legendary.inc"

.section omega_group43_map01_legendary, "aw", %progbits
.include "data/omega/legendary/group43_map01_legendary.inc"

.section omega_group43_map02_legendary, "aw", %progbits
.include "data/omega/legendary/group43_map02_legendary.inc"

.section omega_group43_map03_legendary, "aw", %progbits
.include "data/omega/legendary/group43_map03_legendary.inc"

.section omega_group43_map04_legendary, "aw", %progbits
.include "data/omega/legendary/group43_map04_legendary.inc"

.section omega_group43_map05_legendary, "aw", %progbits
.include "data/omega/legendary/group43_map05_legendary.inc"

.section omega_group43_map06_legendary, "aw", %progbits
.include "data/omega/legendary/group43_map06_legendary.inc"

.section omega_group43_map07_legendary, "aw", %progbits
.include "data/omega/legendary/group43_map07_legendary.inc"

.section omega_group43_map08_legendary, "aw", %progbits
.include "data/omega/legendary/group43_map08_legendary.inc"

.section omega_group43_map09_legendary, "aw", %progbits
.include "data/omega/legendary/group43_map09_legendary.inc"

.section omega_group43_map10_legendary, "aw", %progbits
.include "data/omega/legendary/group43_map10_legendary.inc"

.section omega_group43_map11_legendary, "aw", %progbits
.include "data/omega/legendary/group43_map11_legendary.inc"

.section omega_group43_map12_legendary, "aw", %progbits
.include "data/omega/legendary/group43_map12_legendary.inc"

.section omega_group43_map13_legendary, "aw", %progbits
.include "data/omega/legendary/group43_map13_legendary.inc"

.section omega_group43_map11_warp, "aw", %progbits
.include "data/omega/legendary/group43_map11_warp.inc"

.section omega_group43_map12_warp, "aw", %progbits
.include "data/omega/legendary/group43_map12_warp.inc"

.section omega_group43_map03_trainer, "aw", %progbits
.include "data/omega/legendary/group43_map03_trainer.inc"

.section omega_group43_map04_trainer, "aw", %progbits
.include "data/omega/legendary/group43_map04_trainer.inc"

.section omega_group43_map05_trainer, "aw", %progbits
.include "data/omega/legendary/group43_map05_trainer.inc"

.section omega_group43_map06_trainer, "aw", %progbits
.include "data/omega/legendary/group43_map06_trainer.inc"

.section omega_group43_map07_trainer, "aw", %progbits
.include "data/omega/legendary/group43_map07_trainer.inc"

.section omega_group43_map10_trainer, "aw", %progbits
.include "data/omega/legendary/group43_map10_trainer.inc"

.section omega_group43_map13_trainer1, "aw", %progbits
.include "data/omega/legendary/group43_map13_trainer1.inc"

.section omega_group43_map13_trainer2, "aw", %progbits
.include "data/omega/legendary/group43_map13_trainer2.inc"

.section omega_group43_map03_bg1, "aw", %progbits
.include "data/omega/legendary/group43_map03_bg1.inc"

.section omega_altering_cave_trainer_exact, "aw", %progbits
.include "data/omega/gifts/altering_cave_trainer_exact.inc"

.include "data/omega/gifts/custom_location_aliases.inc"

.section omega_tail_fragment_80408a, "aw", %progbits
.include "data/omega/gifts/tail_fragment_80408a.inc"

.section omega_group43_gap_8041c6, "aw", %progbits
.include "data/omega/legendary/group43_gap_8041c6.inc"

.section omega_expansion_final_byte, "aw", %progbits
.include "data/omega/layout/expansion_final_byte.inc"

.section omega_expansion_exact_803d00_803dff, "aw", %progbits
.include "data/omega/layout/expansion_exact_803d00_803dff.inc"

.section omega_expansion_exact_803e00_803eff, "aw", %progbits
.include "data/omega/layout/expansion_exact_803e00_803eff.inc"

.section omega_expansion_exact_803f00_803fdf, "aw", %progbits
.include "data/omega/layout/expansion_exact_803f00_803fdf.inc"

.section omega_group43_gap_803a8d, "aw", %progbits
.include "data/omega/legendary/group43_gap_803a8d.inc"

.section omega_group43_gap_803bc8, "aw", %progbits
.include "data/omega/legendary/group43_gap_803bc8.inc"

.section omega_group43_gap_803cca, "aw", %progbits
.include "data/omega/legendary/group43_gap_803cca.inc"

.section omega_exact_gap_803000_803014, "aw", %progbits
.include "data/omega/layout/exact_gap_803000_803014.inc"

.section omega_exact_gap_803018_80301f, "aw", %progbits
.include "data/omega/layout/exact_gap_803018_80301f.inc"

.section omega_exact_gap_803021_80302a, "aw", %progbits
.include "data/omega/layout/exact_gap_803021_80302a.inc"

.section omega_exact_gap_80304a_80304a, "aw", %progbits
.include "data/omega/layout/exact_gap_80304a_80304a.inc"

.section omega_exact_gap_80304c_803149, "aw", %progbits
.include "data/omega/layout/exact_gap_80304c_803149.inc"

.section omega_exact_gap_80314d_803154, "aw", %progbits
.include "data/omega/layout/exact_gap_80314d_803154.inc"

.section omega_exact_gap_803156_80315f, "aw", %progbits
.include "data/omega/layout/exact_gap_803156_80315f.inc"

.section omega_exact_gap_80317f_80317f, "aw", %progbits
.include "data/omega/layout/exact_gap_80317f_80317f.inc"

.section omega_exact_gap_803181_8031eb, "aw", %progbits
.include "data/omega/layout/exact_gap_803181_8031eb.inc"

.section omega_exact_gap_80321f_803225, "aw", %progbits
.include "data/omega/layout/exact_gap_80321f_803225.inc"

.section omega_exact_gap_8032c7_8032ce, "aw", %progbits
.include "data/omega/layout/exact_gap_8032c7_8032ce.inc"

.section omega_exact_gap_8032d0_8032f9, "aw", %progbits
.include "data/omega/layout/exact_gap_8032d0_8032f9.inc"

.section omega_exact_gap_8032fb_803357, "aw", %progbits
.include "data/omega/layout/exact_gap_8032fb_803357.inc"

.section omega_exact_gap_803359_803359, "aw", %progbits
.include "data/omega/layout/exact_gap_803359_803359.inc"

.section omega_exact_gap_80335c_803378, "aw", %progbits
.include "data/omega/layout/exact_gap_80335c_803378.inc"

.section omega_exact_gap_80337a_80337a, "aw", %progbits
.include "data/omega/layout/exact_gap_80337a_80337a.inc"

.section omega_exact_gap_80337c_8033bb, "aw", %progbits
.include "data/omega/layout/exact_gap_80337c_8033bb.inc"

.section omega_exact_gap_8033bd_8033e2, "aw", %progbits
.include "data/omega/layout/exact_gap_8033bd_8033e2.inc"

.section omega_exact_gap_80343e_803460, "aw", %progbits
.include "data/omega/layout/exact_gap_80343e_803460.inc"

.section omega_exact_gap_803462_803462, "aw", %progbits
.include "data/omega/layout/exact_gap_803462_803462.inc"

.section omega_exact_gap_803483_80349c, "aw", %progbits
.include "data/omega/layout/exact_gap_803483_80349c.inc"

.section omega_exact_gap_80349e_80349f, "aw", %progbits
.include "data/omega/layout/exact_gap_80349e_80349f.inc"

.section omega_exact_gap_8034a1_8034b6, "aw", %progbits
.include "data/omega/layout/exact_gap_8034a1_8034b6.inc"

.section omega_exact_gap_8034b8_803532, "aw", %progbits
.include "data/omega/layout/exact_gap_8034b8_803532.inc"

.section omega_exact_gap_803534_803534, "aw", %progbits
.include "data/omega/layout/exact_gap_803534_803534.inc"

.section omega_exact_gap_803536_803546, "aw", %progbits
.include "data/omega/layout/exact_gap_803536_803546.inc"

.section omega_exact_gap_803548_803548, "aw", %progbits
.include "data/omega/layout/exact_gap_803548_803548.inc"

.section omega_exact_gap_80354a_80357f, "aw", %progbits
.include "data/omega/layout/exact_gap_80354a_80357f.inc"

.section omega_exact_gap_803581_803598, "aw", %progbits
.include "data/omega/layout/exact_gap_803581_803598.inc"

.section omega_exact_gap_80359a_8035dc, "aw", %progbits
.include "data/omega/layout/exact_gap_80359a_8035dc.inc"

.section omega_exact_gap_8035de_8035de, "aw", %progbits
.include "data/omega/layout/exact_gap_8035de_8035de.inc"

.section omega_exact_gap_8035e0_8035e6, "aw", %progbits
.include "data/omega/layout/exact_gap_8035e0_8035e6.inc"

.section omega_exact_gap_8035e8_8035e8, "aw", %progbits
.include "data/omega/layout/exact_gap_8035e8_8035e8.inc"

.section omega_exact_gap_8035ea_803631, "aw", %progbits
.include "data/omega/layout/exact_gap_8035ea_803631.inc"

.section omega_exact_gap_803633_803633, "aw", %progbits
.include "data/omega/layout/exact_gap_803633_803633.inc"


.section omega_exact_gap_800217_8002f9, "aw", %progbits
.include "data/omega/layout/exact_gap_800217_8002f9.inc"

.section omega_exact_gap_800350_800420, "aw", %progbits
.include "data/omega/layout/exact_gap_800350_800420.inc"

.section omega_exact_gap_8004b0_80052a, "aw", %progbits
.include "data/omega/layout/exact_gap_8004b0_80052a.inc"

.section omega_exact_gap_80054b_80054c, "aw", %progbits
.include "data/omega/layout/exact_gap_80054b_80054c.inc"

.section omega_exact_gap_800567_800568, "aw", %progbits
.include "data/omega/layout/exact_gap_800567_800568.inc"

.section omega_exact_gap_80057f_8005ac, "aw", %progbits
.include "data/omega/layout/exact_gap_80057f_8005ac.inc"

.section omega_exact_gap_8005cf_800995, "aw", %progbits
.include "data/omega/layout/exact_gap_8005cf_800995.inc"

.section omega_exact_gap_800a7b_800af5, "aw", %progbits
.include "data/omega/layout/exact_gap_800a7b_800af5.inc"

.section omega_exact_gap_800b16_800b17, "aw", %progbits
.include "data/omega/layout/exact_gap_800b16_800b17.inc"

.section omega_exact_gap_800b30_800b31, "aw", %progbits
.include "data/omega/layout/exact_gap_800b30_800b31.inc"

.section omega_exact_gap_800b49_800b76, "aw", %progbits
.include "data/omega/layout/exact_gap_800b49_800b76.inc"

.section omega_exact_gap_800b99_800b99, "aw", %progbits
.include "data/omega/layout/exact_gap_800b99_800b99.inc"

.section omega_exact_gap_800c7f_800cf9, "aw", %progbits
.include "data/omega/layout/exact_gap_800c7f_800cf9.inc"

.section omega_exact_gap_800d3b_800d3c, "aw", %progbits
.include "data/omega/layout/exact_gap_800d3b_800d3c.inc"

.section omega_exact_gap_800d5b_800d5c, "aw", %progbits
.include "data/omega/layout/exact_gap_800d5b_800d5c.inc"

.section omega_exact_gap_800d76_800da3, "aw", %progbits
.include "data/omega/layout/exact_gap_800d76_800da3.inc"

.section omega_exact_gap_800dba_800dba, "aw", %progbits
.include "data/omega/layout/exact_gap_800dba_800dba.inc"

.section omega_exact_gap_800f3b_800f3c, "aw", %progbits
.include "data/omega/layout/exact_gap_800f3b_800f3c.inc"

.section omega_exact_gap_800f5c_800f5d, "aw", %progbits
.include "data/omega/layout/exact_gap_800f5c_800f5d.inc"

.section omega_exact_gap_800f76_800fa3, "aw", %progbits
.include "data/omega/layout/exact_gap_800f76_800fa3.inc"

.section omega_exact_gap_800fbd_800fbd, "aw", %progbits
.include "data/omega/layout/exact_gap_800fbd_800fbd.inc"

.section omega_exact_gap_801157_801158, "aw", %progbits
.include "data/omega/layout/exact_gap_801157_801158.inc"

.section omega_exact_gap_801172_801173, "aw", %progbits
.include "data/omega/layout/exact_gap_801172_801173.inc"

.section omega_exact_gap_80118d_8011ba, "aw", %progbits
.include "data/omega/layout/exact_gap_80118d_8011ba.inc"

.section omega_exact_gap_8011d7_80131b, "aw", %progbits
.include "data/omega/layout/exact_gap_8011d7_80131b.inc"

.section omega_exact_gap_8014ac_8014ad, "aw", %progbits
.include "data/omega/layout/exact_gap_8014ac_8014ad.inc"

.section omega_exact_gap_8014ca_8014cb, "aw", %progbits
.include "data/omega/layout/exact_gap_8014ca_8014cb.inc"

.section omega_exact_gap_8014e4_801511, "aw", %progbits
.include "data/omega/layout/exact_gap_8014e4_801511.inc"

.section omega_exact_gap_80152b_80164c, "aw", %progbits
.include "data/omega/layout/exact_gap_80152b_80164c.inc"

.section omega_exact_gap_8017dd_8017de, "aw", %progbits
.include "data/omega/layout/exact_gap_8017dd_8017de.inc"

.section omega_exact_gap_8017fa_8017fb, "aw", %progbits
.include "data/omega/layout/exact_gap_8017fa_8017fb.inc"

.section omega_exact_gap_801815_801842, "aw", %progbits
.include "data/omega/layout/exact_gap_801815_801842.inc"

.section omega_exact_gap_801869_801869, "aw", %progbits
.include "data/omega/layout/exact_gap_801869_801869.inc"

.section omega_exact_gap_80199e_80199f, "aw", %progbits
.include "data/omega/layout/exact_gap_80199e_80199f.inc"

.section omega_exact_gap_8019bc_8019bd, "aw", %progbits
.include "data/omega/layout/exact_gap_8019bc_8019bd.inc"

.section omega_exact_gap_8019d8_801a05, "aw", %progbits
.include "data/omega/layout/exact_gap_8019d8_801a05.inc"

.section omega_exact_gap_801a28_801c4d, "aw", %progbits
.include "data/omega/layout/exact_gap_801a28_801c4d.inc"

.section omega_exact_gap_801d34_801dad, "aw", %progbits
.include "data/omega/layout/exact_gap_801d34_801dad.inc"

.section omega_exact_gap_801e18_801e19, "aw", %progbits
.include "data/omega/layout/exact_gap_801e18_801e19.inc"

.section omega_exact_gap_801e41_801e42, "aw", %progbits
.include "data/omega/layout/exact_gap_801e41_801e42.inc"

.section omega_exact_gap_801e5a_801e87, "aw", %progbits
.include "data/omega/layout/exact_gap_801e5a_801e87.inc"

.section omega_exact_gap_801ea7_801fff, "aw", %progbits
.include "data/omega/layout/exact_gap_801ea7_801fff.inc"
