	.global OmegaGroup43_Map00_MapEvents
	.set OmegaGroup43_Map00_MapEvents, 0x08722B50
	.global OmegaGroup43_Map01_MapEvents
	.set OmegaGroup43_Map01_MapEvents, 0x08722BC0
	.global OmegaGroup43_Map02_MapEvents
	.set OmegaGroup43_Map02_MapEvents, 0x08721A7C
	.global OmegaGroup43_Map03_MapEvents
	.set OmegaGroup43_Map03_MapEvents, 0x0871C2D8
	.global OmegaGroup43_Map04_MapEvents
	.set OmegaGroup43_Map04_MapEvents, 0x08723FD0
	.global OmegaGroup43_Map05_MapEvents
	.set OmegaGroup43_Map05_MapEvents, 0x0872C86C
	.global OmegaGroup43_Map06_MapEvents
	.set OmegaGroup43_Map06_MapEvents, 0x0872C8C0
	.global OmegaGroup43_Map07_MapEvents
	.set OmegaGroup43_Map07_MapEvents, 0x0872C914
	.global OmegaGroup43_Map08_MapEvents
	.set OmegaGroup43_Map08_MapEvents, 0x087280D0
	.global OmegaGroup43_Map09_MapEvents
	.set OmegaGroup43_Map09_MapEvents, 0x08728DFC
	.global OmegaGroup43_Map10_MapEvents
	.set OmegaGroup43_Map10_MapEvents, 0x0872C9AC
	.global OmegaGroup43_Map11_MapEvents
	.set OmegaGroup43_Map11_MapEvents, 0x0872AEA0
	.global OmegaGroup43_Map12_MapEvents
	.set OmegaGroup43_Map12_MapEvents, 0x0871C230
	.global OmegaGroup43_Map13_MapEvents
	.set OmegaGroup43_Map13_MapEvents, 0x0872CA6C
