	.global OmegaGroup43_Map00_Layout_Border
	.set OmegaGroup43_Map00_Layout_Border, 0x08722100
	.global OmegaGroup43_Map00_Layout_Blockdata
	.set OmegaGroup43_Map00_Layout_Blockdata, 0x08722108
	.global OmegaGroup43_Map00_Layout
	.set OmegaGroup43_Map00_Layout, 0x08722428
	.global OmegaGroup43_Map00
	.set OmegaGroup43_Map00, 0x087220E4
	.global OmegaGroup43_Map01_Layout_Border
	.set OmegaGroup43_Map01_Layout_Border, 0x08722460
	.global OmegaGroup43_Map01_Layout_Blockdata
	.set OmegaGroup43_Map01_Layout_Blockdata, 0x08722468
	.global OmegaGroup43_Map01_Layout
	.set OmegaGroup43_Map01_Layout, 0x08722788
	.global OmegaGroup43_Map01
	.set OmegaGroup43_Map01, 0x08722444
	.global OmegaGroup43_Map02_Layout_Border
	.set OmegaGroup43_Map02_Layout_Border, 0x087227C0
	.global OmegaGroup43_Map02_Layout_Blockdata
	.set OmegaGroup43_Map02_Layout_Blockdata, 0x087227C8
	.global OmegaGroup43_Map02_Layout
	.set OmegaGroup43_Map02_Layout, 0x08722AE8
	.global OmegaGroup43_Map02
	.set OmegaGroup43_Map02, 0x087227A4
	.global OmegaGroup43_Map03_Layout_Border
	.set OmegaGroup43_Map03_Layout_Border, 0x087232EC
	.global OmegaGroup43_Map03_Layout_Blockdata
	.set OmegaGroup43_Map03_Layout_Blockdata, 0x087232F4
	.global OmegaGroup43_Map03_Layout
	.set OmegaGroup43_Map03_Layout, 0x08723F74
	.global OmegaGroup43_Map03
	.set OmegaGroup43_Map03, 0x087232D0
	.global OmegaGroup43_Map04_Layout_Border
	.set OmegaGroup43_Map04_Layout_Border, 0x0872400C
	.global OmegaGroup43_Map04_Layout_Blockdata
	.set OmegaGroup43_Map04_Layout_Blockdata, 0x08724014
	.global OmegaGroup43_Map04_Layout
	.set OmegaGroup43_Map04_Layout, 0x08724C94
	.global OmegaGroup43_Map04
	.set OmegaGroup43_Map04, 0x08723FF0
	.global OmegaGroup43_Map05_Layout_Border
	.set OmegaGroup43_Map05_Layout_Border, 0x08724D08
	.global OmegaGroup43_Map05_Layout_Blockdata
	.set OmegaGroup43_Map05_Layout_Blockdata, 0x08724D10
	.global OmegaGroup43_Map05_Layout
	.set OmegaGroup43_Map05_Layout, 0x08725990
	.global OmegaGroup43_Map05
	.set OmegaGroup43_Map05, 0x08724CEC
	.global OmegaGroup43_Map06_Layout_Border
	.set OmegaGroup43_Map06_Layout_Border, 0x08725A04
	.global OmegaGroup43_Map06_Layout_Blockdata
	.set OmegaGroup43_Map06_Layout_Blockdata, 0x08725A0C
	.global OmegaGroup43_Map06_Layout
	.set OmegaGroup43_Map06_Layout, 0x0872668C
	.global OmegaGroup43_Map06
	.set OmegaGroup43_Map06, 0x087259E8
	.global OmegaGroup43_Map07_Layout_Border
	.set OmegaGroup43_Map07_Layout_Border, 0x08726700
	.global OmegaGroup43_Map07_Layout_Blockdata
	.set OmegaGroup43_Map07_Layout_Blockdata, 0x08726708
	.global OmegaGroup43_Map07_Layout
	.set OmegaGroup43_Map07_Layout, 0x08727388
	.global OmegaGroup43_Map07
	.set OmegaGroup43_Map07, 0x087266E4
	.global OmegaGroup43_Map08_Layout_Border
	.set OmegaGroup43_Map08_Layout_Border, 0x087273FC
	.global OmegaGroup43_Map08_Layout_Blockdata
	.set OmegaGroup43_Map08_Layout_Blockdata, 0x08727404
	.global OmegaGroup43_Map08_Layout
	.set OmegaGroup43_Map08_Layout, 0x08728084
	.global OmegaGroup43_Map08
	.set OmegaGroup43_Map08, 0x087273E0
	.global OmegaGroup43_Map09_Layout_Border
	.set OmegaGroup43_Map09_Layout_Border, 0x08728100
	.global OmegaGroup43_Map09_Layout_Blockdata
	.set OmegaGroup43_Map09_Layout_Blockdata, 0x08728108
	.global OmegaGroup43_Map09_Layout
	.set OmegaGroup43_Map09_Layout, 0x08728D88
	.global OmegaGroup43_Map09
	.set OmegaGroup43_Map09, 0x087280E4
	.global OmegaGroup43_Map10_Layout_Border
	.set OmegaGroup43_Map10_Layout_Border, 0x0872947C
	.global OmegaGroup43_Map10_Layout_Blockdata
	.set OmegaGroup43_Map10_Layout_Blockdata, 0x08729484
	.global OmegaGroup43_Map10_Layout
	.set OmegaGroup43_Map10_Layout, 0x0872A104
	.global OmegaGroup43_Map10
	.set OmegaGroup43_Map10, 0x08729460
	.global OmegaGroup43_Map11_Layout_Border
	.set OmegaGroup43_Map11_Layout_Border, 0x0872A1BC
	.global OmegaGroup43_Map11_Layout_Blockdata
	.set OmegaGroup43_Map11_Layout_Blockdata, 0x0872A1C4
	.global OmegaGroup43_Map11_Layout
	.set OmegaGroup43_Map11_Layout, 0x0872AE44
	.global OmegaGroup43_Map11
	.set OmegaGroup43_Map11, 0x0872A1A0
	.global OmegaGroup43_Map12_Layout_Border
	.set OmegaGroup43_Map12_Layout_Border, 0x0872AED0
	.global OmegaGroup43_Map12_Layout_Blockdata
	.set OmegaGroup43_Map12_Layout_Blockdata, 0x0872AEDC
	.global OmegaGroup43_Map12_Layout
	.set OmegaGroup43_Map12_Layout, 0x0872B5E4
	.global OmegaGroup43_Map12
	.set OmegaGroup43_Map12, 0x0872AEB4
	.global OmegaGroup43_Map13_Layout_Border
	.set OmegaGroup43_Map13_Layout_Border, 0x0872B85C
	.global OmegaGroup43_Map13_Layout_Blockdata
	.set OmegaGroup43_Map13_Layout_Blockdata, 0x0872B864
	.global OmegaGroup43_Map13_Layout
	.set OmegaGroup43_Map13_Layout, 0x0872C3A4
	.global OmegaGroup43_Map13
	.set OmegaGroup43_Map13, 0x0872B840
	.global gMapLayouts
	.set gMapLayouts, 0x08728E10
	.global gMapGroup_OmegaGroup43
	.set gMapGroup_OmegaGroup43, 0x0871C178
	.global gMapGroups
	.set gMapGroups, 0x0871BE34
