	.global BirthIsland_Exterior_MapEvents
	.set BirthIsland_Exterior_MapEvents, 0x0872A170
	.global CeladonCity_MapEvents
	.set CeladonCity_MapEvents, 0x08721F20
	.global CeruleanCave_1F_MapEvents
	.set CeruleanCave_1F_MapEvents, 0x0872C684
	.global CeruleanCave_2F_MapEvents
	.set CeruleanCave_2F_MapEvents, 0x0872C818
	.global CeruleanCave_B1F_MapEvents
	.set CeruleanCave_B1F_MapEvents, 0x0872C534
	.global IndigoPlateau_PokemonCenter_1F_MapEvents
	.set IndigoPlateau_PokemonCenter_1F_MapEvents, 0x083BCA94
	.global MtEmber_Exterior_MapEvents
	.set MtEmber_Exterior_MapEvents, 0x08722E78
	.global PewterCity_MapEvents
	.set PewterCity_MapEvents, 0x08721CB8
	.global PewterCity_PokemonCenter_1F_MapEvents
	.set PewterCity_PokemonCenter_1F_MapEvents, 0x0871B3A8
	.global PokemonTower_1F_MapEvents
	.set PokemonTower_1F_MapEvents, 0x0871C164
	.global RockTunnel_B1F_MapEvents
	.set RockTunnel_B1F_MapEvents, 0x083B1DD0
	.global Route10_MapEvents
	.set Route10_MapEvents, 0x0871C0A0
	.global Route11_MapEvents
	.set Route11_MapEvents, 0x087220B4
	.global Route20_MapEvents
	.set Route20_MapEvents, 0x0872CBD4
	.global Route24_MapEvents
	.set Route24_MapEvents, 0x0871B5C8
	.global Route2_ViridianForest_NorthEntrance_MapEvents
	.set Route2_ViridianForest_NorthEntrance_MapEvents, 0x0871B2B4
	.global Route4_MapEvents
	.set Route4_MapEvents, 0x083B6980
	.global Route6_MapEvents
	.set Route6_MapEvents, 0x0871BAC8
	.global Route9_MapEvents
	.set Route9_MapEvents, 0x0871BC5C
	.global SafariZone_East_MapEvents
	.set SafariZone_East_MapEvents, 0x0871E8E4
	.global SafariZone_North_MapEvents
	.set SafariZone_North_MapEvents, 0x0871FC00
	.global SafariZone_SecretHouse_MapEvents
	.set SafariZone_SecretHouse_MapEvents, 0x0871BDE8
	.global SafariZone_West_MapEvents
	.set SafariZone_West_MapEvents, 0x08720ABC
	.global SixIsland_AlteringCave_MapEvents
	.set SixIsland_AlteringCave_MapEvents, 0x087230D8
	.global SixIsland_OutcastIsland_MapEvents
	.set SixIsland_OutcastIsland_MapEvents, 0x0871A778
	.global TwoIsland_CapeBrink_MapEvents
	.set TwoIsland_CapeBrink_MapEvents, 0x08722B8C
	.global UndergroundPath_SouthEntrance_MapEvents
	.set UndergroundPath_SouthEntrance_MapEvents, 0x0871B898
	.global VermilionCity_MapEvents
	.set VermilionCity_MapEvents, 0x0872B82C

	.global CeladonCity_Condominiums_2F_MapEvents
	.set CeladonCity_Condominiums_2F_MapEvents, 0x083B5F44
	.global CeladonCity_GameCorner_MapEvents
	.set CeladonCity_GameCorner_MapEvents, 0x0871C754
	.global CeruleanCity_MapEvents
	.set CeruleanCity_MapEvents, 0x0871B834
	.global FiveIsland_WaterLabyrinth_MapEvents
	.set FiveIsland_WaterLabyrinth_MapEvents, 0x0872CEDC
	.global OneIsland_KindleRoad_MapEvents
	.set OneIsland_KindleRoad_MapEvents, 0x0872FA9C
	.global RockTunnel_1F_MapEvents
	.set RockTunnel_1F_MapEvents, 0x0871C450
	.global Route2_MapEvents
	.set Route2_MapEvents, 0x0871A64C
	.global SafariZone_Center_MapEvents
	.set SafariZone_Center_MapEvents, 0x0871D910
	.global SaffronCity_MapEvents
	.set SaffronCity_MapEvents, 0x0871C9CC
	.global ThreeIsland_BondBridge_MapEvents
	.set ThreeIsland_BondBridge_MapEvents, 0x08722FB8
	.global ViridianCity_MapEvents
	.set ViridianCity_MapEvents, 0x0871A48C
